# Generated by Django 4.1.5 on 2023-01-31 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadmanagement',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
