# Generated by Django 4.1.5 on 2023-01-31 11:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_leadmanagement_date_modified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leadmanagement',
            name='index',
        ),
        migrations.AlterField(
            model_name='leadmanagement',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
